### ISSUE TITLE
Дужкі ў назвах гарадоў ды адсутныя назвы краiн

### ISSUE THREAD

**Issue by abitrolly** [osm-by/OpenStreetMap.by#19]
From @tbicr

![image](https://user-images.githubusercontent.com/8781107/81793023-7baadf80-9511-11ea-8a25-5b18c6f8a352.png)

> Хацеў бы каб не было дужак і таго што ў іх

From @tbicr #2 

![image](https://user-images.githubusercontent.com/8781107/81793414-04298000-9512-11ea-915f-1f349f564b45.png)

> Хацеў бы каб былі надпісы для ўсіх краінаў

**Comment by abitrolly** [comment]
3 from @tbicr

![image](https://user-images.githubusercontent.com/8781107/81794332-4bfcd700-9513-11ea-9653-539fef946fbb.png)

> было б добра мець налады для выбару лёгікі для асноўнага і альтэрнатыўнага надпісу на ляту

**Comment by abitrolly** [comment]
Ад чаго залежыць цi малююцца лi дужкi. Ад @tbicr 

> 1. ці ёсць значэньне ў osm name тэзе, 2. ці ёсьць у wikidata, 3. ці напісана лёгіка каб апрацоўваць нават не ідэальныя дадзеныя

> тут ці самі дадзеныя недакладныя, ці імпарт дадзеных не апрацоўае дадзены кейс, ці гетерацыя тайлаў не апрацоўвае дадзены кейс, ці рэндэр не апрацоўвае дадзены кейс

**Comment by tbicr** [comment]
выпраўлена ў #24
